# host: http://yourhost.com
meta:
  analytics: 'UA-12345678-1'
  title: your title
  header: your header
  author:
    name: your name
    short_name: you
    email: youremail@yourhost.com
    github: you
    twitter: you
